Repository tophat/RichTextView, pull requests merged in 2019-12, with the labels that each got.

#126 feat: Add attributes to strings
  Example/Source/InputOutputModuleView.swift
  Example/Source/ViewController.swift
  Podfile.lock
  Source/Extensions/NSMutableAttributedStringExtension.swift
  Source/RichTextView.swift
  Source/Text Parsing/RichTextParser.swift
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_highlights@2x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Update__Updates_highlight_Color_Properly@2x.png
  UITests/RichTextViewUITests.swift
  UnitTests/Text Parsing/RichTextParserSpec.swift
Labels: approved

#128 fix: fixed StringExtension.split method in order to avoid out of bounds crash
  Example/Podfile.lock
  Podfile.lock
  Source/Extensions/StringExtension.swift
  UnitTests/Extensions/StringExtensionSpec.swift
Labels: approved

#127 feat: Add underline style to highlighted text
  Source/Text Parsing/RichTextParser.swift
  UnitTests/Text Parsing/RichTextParserSpec.swift
Labels: approved

#129 fix: perserve spaces before and after special elements
  Source/Extensions/StringExtension.swift
  Source/Text Parsing/RichTextParser.swift
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_LaTeX_and_a_custom_baseline_offset@2x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_highlights@2x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Update__Updates_highlight_Color_Properly@2x.png
  UITests/RichTextViewUITests.swift
  UnitTests/Extensions/StringExtensionSpec.swift
  UnitTests/Text Parsing/RichTextParserSpec.swift
Labels: approved

#130 fix: Table rendering issues - Bugfix/iOS 7209
  Example/Podfile.lock
  Example/Source/ViewController.swift
  Podfile
  Podfile.lock
  RichTextView.podspec
  Source/Text Parsing/RichTextParser.swift
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_regular_string_with_no_rich_text_formatting@2x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_regular_string_with_no_rich_text_formatting@3x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_HTML@2x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_HTML@3x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_LaTeX@3x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_LaTeX_and_a_custom_baseline_offset@2x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_LaTeX_and_a_custom_baseline_offset@3x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_Markdown@2x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_Markdown@3x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_highlights@2x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_highlights@3x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Update__Updates_Font_Properly@2x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Update__Updates_Font_Properly@3x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Update__Updates_Input_Properly@2x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Update__Updates_Input_Properly@3x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Update__Updates_Text_Color_Properly@2x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Update__Updates_Text_Color_Properly@3x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Update__Updates_highlight_Color_Properly@2x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Update__Updates_highlight_Color_Properly@3x.png
Labels: reviewme

#131 fix: add UTF8 encoding to NSattributed strings
  Source/Text Parsing/RichTextParser.swift
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_LaTeX_and_a_custom_baseline_offset@2x.png
Labels: approved, devQA-approved

#132 fix: LaTeX Expressions are misaligned in the textbook
  Example/Source/ViewController.swift
  Source/Text Parsing/LatexParserProtocol.swift
  Source/Text Parsing/RichTextParser.swift
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_LaTeX@2x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_LaTeX@3x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_LaTeX_and_a_custom_baseline_offset@2x.png
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_LaTeX_and_a_custom_baseline_offset@3x.png
Labels: approved
