Repository tophat/RichTextView, pull requests merged in 2019-09, with the labels that each got.

#113 feat: Rich text accessibility
  RichTextView.xcodeproj/project.pbxproj
  Source/RichTextView.swift
  UnitTests/RichTextViewSpec.swift
Labels: approved, devQA-approved

#114 fix: Update RichTextParser.swift to also consume interactive element attributes.
  Source/Text Parsing/RichTextParser.swift
  UnitTests/Text Parsing/RichTextParserSpec.swift
Labels: approved

#115 fix: Update RichTextParser.swift to have regex for interactive elements not be greedy.
  Source/Text Parsing/RichTextParser.swift
  UnitTests/Extensions/StringExtensionSpec.swift
Labels: approved, devQA-approved

#116 fix: Remove leading space in interactive element regex
  Source/Text Parsing/RichTextParser.swift
Labels: reviewme

#117 fix: Stop Down from Dropping Latex characters
  Example/RichTextView-Example.xcodeproj/xcshareddata/xcschemes/RichTextView-Example.xcscheme
  Podfile.lock
  RichTextView.xcodeproj/project.pbxproj
  Source/Extensions/NSMutableAttributedStringExtension.swift
  Source/Extensions/StringExtension.swift
  Source/Text Parsing/RichTextParser.swift
  UITests/ReferenceImages/RichTextViewUITests/RichTextView_UI__Rendering_Various_Strings_of_Rich_Text__Renders_a_string_with_LaTeX_and_a_custom_baseline_offset@2x.png
  UnitTests/Extensions/NSMutableAttributedStringExtensionSpec.swift
  UnitTests/Extensions/StringExtensionSpec.swift
Labels: approved, devQA-approved

#119 fix: String Extension Crash
  Source/Text Parsing/RichTextParser.swift
Labels: approved, devQA-approved
